modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
issueTrackerURL="https://github.com/Fourmisain/AxesAreWeapons/issues"

[[mods]]
modId="axesareweapons"
version="${mod_version}"
displayName="Axes Are Weapons"
displayURL="https://www.curseforge.com/minecraft/mc-mods/axes-are-weapons"
logoFile= "icon.png"
authors="Fourmisain"
description='''
Disables the increased durability loss in combat.
'''
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.axesareweapons]]
modId="forge"
mandatory=true
versionRange="[44.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.axesareweapons]]
modId="minecraft"
mandatory=true
versionRange="${forge_game_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.axesareweapons]]
modId="cloth_config"
mandatory=true
versionRange="[9.0.0,)"
ordering="NONE"
side="BOTH"